### ISSUE TITLE
access permission

### ISSUE THREAD

**Issue by pimarc** [dga711/devtools-backend-refurb#1]
Hello
I'd like to use your tool but it seems I do not have the authorization to clone it.
I wrote a well-appreciated MOD for GNS530 GPS and this tool (or some other you may have) should help me.
Thanks if you can give me the access.

**Comment by dga711** [comment]
Hi,
can you contact me on Discord? dga#6992

This thing in this repo is basically abandoned as there will never be a chance to do js debugging with it. But I have something going, which I cant put up for public download, that will allow you to debug.
